//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicApp.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have entered at least 1 {PropertyName}.
        /// </summary>
        public static string AlbumGenresCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("AlbumGenresCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have entered the correct {PropertyName}.
        /// </summary>
        public static string AlbumGenresCheckValidGenre {
            get {
                return ResourceManager.GetString("AlbumGenresCheckValidGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string AlbumNameCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("AlbumNameCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName} length from 4 to 30 characters.
        /// </summary>
        public static string AlbumNameCheckLength {
            get {
                return ResourceManager.GetString("AlbumNameCheckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {PropertyName} it should not be empty, please fill in this field.
        /// </summary>
        public static string AlbumReleaseCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("AlbumReleaseCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the correct {PropertyName}.
        /// </summary>
        public static string AlbumReleaseCheckItIsADate {
            get {
                return ResourceManager.GetString("AlbumReleaseCheckItIsADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the correct {PropertyName}.
        /// </summary>
        public static string AlbumReleaseShouldNotBeFuture {
            get {
                return ResourceManager.GetString("AlbumReleaseShouldNotBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string AlbumSortByCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("AlbumSortByCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct value: EP or LP.
        /// </summary>
        public static string AlbumTypeCheckCorrectValue {
            get {
                return ResourceManager.GetString("AlbumTypeCheckCorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string AlbumTypeCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("AlbumTypeCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string ArtistDescriptionCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("ArtistDescriptionCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName} length from 30 to 1500 characters.
        /// </summary>
        public static string ArtistDescriptionCheckLength {
            get {
                return ResourceManager.GetString("ArtistDescriptionCheckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have entered at least 1 {PropertyName}.
        /// </summary>
        public static string ArtistGenresCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("ArtistGenresCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have entered the correct {PropertyName}.
        /// </summary>
        public static string ArtistGenresCheckValidGenre {
            get {
                return ResourceManager.GetString("ArtistGenresCheckValidGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string ArtistNameCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("ArtistNameCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName} length from 4 to 30 characters.
        /// </summary>
        public static string ArtistNameCheckLength {
            get {
                return ResourceManager.GetString("ArtistNameCheckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artist has been found for this ID.
        /// </summary>
        public static string ArtistNotFoundByThisId {
            get {
                return ResourceManager.GetString("ArtistNotFoundByThisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtistId or AlbumId not found.
        /// </summary>
        public static string ArtistOrAlbumIsNotFound {
            get {
                return ResourceManager.GetString("ArtistOrAlbumIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to create an album of this artist, so the id was not found..
        /// </summary>
        public static string NotPossibleToCreateAlbum {
            get {
                return ResourceManager.GetString("NotPossibleToCreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter desc or asc.
        /// </summary>
        public static string OrderByCheckValues {
            get {
                return ResourceManager.GetString("OrderByCheckValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a non-negative {PropertyName}.
        /// </summary>
        public static string PageNumberCheckValidInput {
            get {
                return ResourceManager.GetString("PageNumberCheckValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a non-negative {PropertyName}.
        /// </summary>
        public static string PageSizeCheckValidInput {
            get {
                return ResourceManager.GetString("PageSizeCheckValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than 0.
        /// </summary>
        public static string SongDurationInSecondsPositiveCheck {
            get {
                return ResourceManager.GetString("SongDurationInSecondsPositiveCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName} length from 4 to 30 characters.
        /// </summary>
        public static string SongNameCheckCorrectLength {
            get {
                return ResourceManager.GetString("SongNameCheckCorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your {PropertyName}.
        /// </summary>
        public static string SongNameCheckIsNotEmpty {
            get {
                return ResourceManager.GetString("SongNameCheckIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than 0.
        /// </summary>
        public static string SongNumberPositiveCheck {
            get {
                return ResourceManager.GetString("SongNumberPositiveCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct values for sorting {0}.
        /// </summary>
        public static string SortByCheckCorrectValues {
            get {
                return ResourceManager.GetString("SortByCheckCorrectValues", resourceCulture);
            }
        }
    }
}
